# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{silver}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Erik Hin-tone"]
  s.date = %q{2011-01-31}
  s.description = %q{A lightweight, Redis-backed cacher and indexer for databases, REST API's, really anything you can query.}
  s.email = %q{hinton.erik@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/silver.rb",
    "lib/silver/cache.rb",
    "lib/silver/common_words.rb",
    "lib/silver/indexer.rb",
    "lib/silver/search.rb",
    "silver.gemspec",
    "spec/silver_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/db.rb",
    "spec/support/spec.db"
  ]
  s.homepage = %q{http://github.com/tpm/silver}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Makes your queries faster with the power of Redis.}
  s.test_files = [
    "spec/silver_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/db.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<redis>, ["~> 2.1.1"])
      s.add_development_dependency(%q<yajl-ruby>, [">= 0.7.7"])
      s.add_development_dependency(%q<text>, ["~> 0.2.0"])
      s.add_development_dependency(%q<dm-core>, ["~> 1.0.0"])
      s.add_development_dependency(%q<dm-sqlite-adapter>, ["~> 1.0.0"])
      s.add_runtime_dependency(%q<redis>, ["~> 2.1.1"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0.7.7"])
      s.add_runtime_dependency(%q<text>, ["~> 0.2.0"])
      s.add_development_dependency(%q<dm-core>, ["~> 1.0.0"])
      s.add_development_dependency(%q<dm-sqlite-adapter>, ["~> 1.0.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<redis>, ["~> 2.1.1"])
      s.add_dependency(%q<yajl-ruby>, [">= 0.7.7"])
      s.add_dependency(%q<text>, ["~> 0.2.0"])
      s.add_dependency(%q<dm-core>, ["~> 1.0.0"])
      s.add_dependency(%q<dm-sqlite-adapter>, ["~> 1.0.0"])
      s.add_dependency(%q<redis>, ["~> 2.1.1"])
      s.add_dependency(%q<yajl-ruby>, [">= 0.7.7"])
      s.add_dependency(%q<text>, ["~> 0.2.0"])
      s.add_dependency(%q<dm-core>, ["~> 1.0.0"])
      s.add_dependency(%q<dm-sqlite-adapter>, ["~> 1.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<redis>, ["~> 2.1.1"])
    s.add_dependency(%q<yajl-ruby>, [">= 0.7.7"])
    s.add_dependency(%q<text>, ["~> 0.2.0"])
    s.add_dependency(%q<dm-core>, ["~> 1.0.0"])
    s.add_dependency(%q<dm-sqlite-adapter>, ["~> 1.0.0"])
    s.add_dependency(%q<redis>, ["~> 2.1.1"])
    s.add_dependency(%q<yajl-ruby>, [">= 0.7.7"])
    s.add_dependency(%q<text>, ["~> 0.2.0"])
    s.add_dependency(%q<dm-core>, ["~> 1.0.0"])
    s.add_dependency(%q<dm-sqlite-adapter>, ["~> 1.0.0"])
  end
end

